info:
  name: Config Server

server:
  port: 8200


#rabbitmq的地址、用户名和密码
spring:
  rabbitmq:
    host: 172.16.4.39
    username: rabbitmq
    password: rabbitmq
  profiles:
    active: dev

#使得/refresh不需要权限验证
management:
  security:
    enabled: false
#访问时需要提供用户名和密码
security:
  #/monitor接口用于接收git刷新通知，不需要用户名密码校验
  ignored: /monitor, /encrypt
  user:
    name: chenxyz
    password: 123

#经过一番踩坑，encrypt.key必须写在bootstrap文件里面才能生效
#encrypt:
#  #秘钥
#  key: 123

# 不同环境的配置
---
spring:
  profiles: dev
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    preferIpAddress: true
---
spring:
  profiles: production
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/,http://eureka3:8763/eureka/
  instance:
    preferIpAddress: true

