spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
#eureka配置
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://eureka1:8761/eureka/
  instance:
    #心跳间隔
    lease-renewal-interval-in-seconds: 30
---
spring:
  profiles: production
#eureka配置
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://eureka1:8761/eureka/,http://eureka1:8762/eureka/,http://eureka3:8761/eureka/
  instance:
    #心跳间隔
    lease-renewal-interval-in-seconds: 30
