info:
  name: SMS service

server:
  port: 8001

#eureka配置
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://127.0.0.1:8761/eureka/
  instance:
    #心跳间隔
    lease-renewal-interval-in-seconds: 30

