info:
  name: SMS service

#调用refresh的时候不校验权限
management:
  security:
    enabled: false

spring:
  profiles:
    active: dev
  rabbitmq:
      host: 172.16.4.39
      username: rabbitmq
      password: rabbitmq
  zipkin:
    locator:
      discovery:
        enabled: false
    base-url: http://localhost:8400
  sleuth:
    sampler:
      percentage: 1.0

sms:
  registerMsg: 您的注册码为{code},此验证码一分钟内有效,如果不是本人操作请忽略。

---
spring:
  profiles: dev
server:
  port: 8001
---
spring:
  profiles: prod
server:
  port: 9001