info:
  name: User service

spring:
  profiles:
    active: dev

#eureka配置
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://eureka1:8761/eureka/
  instance:
    #心跳间隔
    lease-renewal-interval-in-seconds: 30

---
spring:
  profiles: dev
server:
  port: 8002
---
spring:
  profiles: prod
server:
  port: 9002

