info:
  name: Zipkin Server

server:
  port: 8400

#不设置为false，就不能调用/routes获取路由表
management:
  security:
    enabled: false

#eureka配置
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://eureka1:8761/eureka/
  instance:
    #心跳间隔
    lease-renewal-interval-in-seconds: 30