info:
  name: Zipkin Server

server:
  port: 8400

#不设置为false，就不能调用/routes获取路由表
management:
  security:
    enabled: false

spring:
  datasource:
    schema: classpath:ysql.sql
    # zipkin-autoconfigure-storage-mysql包中默认包含了HikariDataSource
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/test
    username: chenxyz
    password: 123
    # Switch this on to create the schema on startup:
    initialize: true
    continueOnError: true

# 设置存储类型为mysql
zipkin:
  storage:
    type: mysql

#eureka配置
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://eureka1:8761/eureka/
  instance:
    #心跳间隔
    lease-renewal-interval-in-seconds: 30